use_frameworks!

platform :ios, '11.0'

target 'VandMarvelUIKit_Example' do
  pod 'VandMarvelUIKit', :path => '../'

  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'

  target 'UITests' do
    inherit! :search_paths

    
  end
end
